Feat/testing kpi staff controller
Candidate-College/new-api-weekly-report pull request #47
Opened 2024-09-12 17:10 UTC by NaufalMuh11

# Description

This pull request includes the following changes:

1. Addition of Database Transaction for Each Test:
     - Isolates new data created during testing to ensure a clean state for each test run.

2. Seeder Changes:
     - Updated the seeder to use `\database\db_new_api_weekly_report.sql`
     - Instructions to run the seeder after migration: php artisan db:seed.
     
3. Testing for Controllers:
    - Added tests for DivisionKpiController.
    - Added tests for FeedbackController.
    - Added tests for StaffKpiController.
 
Type of Change
- [ ]  New feature (non-breaking change which adds functionality)

## Additional Notes:

- Ensure to run `php artisan migrate` before seeding the database.
- To seed the database, run: `php artisan db:seed`
- Run test with `php artisan test`

2024-09-13 10:31 UTC, nugrahaAdhitama requested changes
# Code Review: `tests/Feature/DivisionKPITest.php`

## General Observations
- The tests cover various critical paths, including authorization, validation, and business rules, ensuring a well-rounded suite.
- The usage of `beforeEach` and `afterEach` hooks to manage database transactions is a great way to ensure tests are isolated.
- Assertions are consistent and clearly written, making the tests easy to follow.
- Good usage of Laravel’s response status codes, particularly for handling 403 and 422 errors.

## Specific Feedback

### **Scope 1: Duplication of Authorization Checks**
- **Issue**: Authorization checks are repeated across multiple test cases (e.g., checking if the user is unauthorized as a non-supervisor or clevel).
- **Suggestion**: Consider creating helper methods to avoid code duplication and improve test readability. For example, a method like `assertForbiddenForNonSupervisor()` could be reused across tests.

### **Scope 2: Hard-coded Email and Password Values**
- **Issue**: The hard-coded credentials (e.g., `ward.ruecker@example.com`, `'rahasia'`) reduce flexibility and scalability in the long term, and make the tests harder to maintain.
- **Suggestion**: Use factories or predefined constants to store test users and their credentials. This will make the code easier to update if credentials change or new users are added.

### **Scope 3: Lack of Data Validation Beyond Simple Errors**
- **Issue**: The tests validate simple errors like forbidden actions or incorrect data types but don’t seem to cover edge cases like missing fields or boundary values (e.g., negative weights).
- **Suggestion**: Add more test cases for edge scenarios, such as weights exceeding 100 or missing KPI fields. This will make your test coverage more comprehensive.

### **Scope 4: Use of `expect` Instead of Laravel Assertions**
- **Issue**: You're using `expect` for your assertions, which, while readable, doesn’t fully leverage Laravel’s built-in testing features, such as `assertForbidden()` or `assertJsonValidationErrors()`.
- **Suggestion**: Consider using Laravel’s built-in testing methods for better readability and adherence to Laravel conventions. For instance, replace `expect($response->status())->toBe(403)` with `$response->assertForbidden()`.

### **Scope 5: Insufficient Test Coverage for GET Requests**
- **Issue**: The tests for GET requests focus heavily on error scenarios like unauthorized access or data not found. There’s less emphasis on testing valid responses.
- **Suggestion**: Include more positive test cases for valid GET requests, including different months, years, or scenarios where partial data may exist.

## Conclusion
Overall, the tests achieve their goal of covering core API paths for the KPI feature. However, there are several areas where improvements can be made to enhance maintainability and scalability. Introducing helper methods to reduce code duplication, using Laravel’s built-in assertion methods, and expanding test coverage to include edge cases will help you align better with clean code principles and best practices in unit testing. These changes will also ensure that the tests remain readable, maintainable, and effective as the system evolves. Keep up the good work!

2024-09-14 00:35 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
> +        $staffToken = authenticateAs('turner.emmet@example.org', 'rahasia');
This is just used as a variable

2024-09-14 00:35 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
> +        $staffToken = authenticateAs('turner.emmet@example.org', 'rahasia');
This is just used as a variable

2024-09-14 00:35 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
>          $supervisorToken = authenticateAs('ward.ruecker@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:35 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
> +        $supervisorToken = authenticateAs('ward.ruecker@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:36 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
>          $staffToken = authenticateAs('turner.emmet@example.org', 'rahasia');
This is also used as a variable

2024-09-14 00:36 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
>          $supervisorToken = authenticateAs('ward.ruecker@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:36 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
>          $supervisorToken = authenticateAs('ward.ruecker@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:36 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
> +        $supervisorToken = authenticateAs('ward.ruecker@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:37 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
> +        $supervisorToken = authenticateAs('karolann97@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:37 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
> +        $supervisorToken = authenticateAs('josue60@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:37 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
> +        $supervisorToken = authenticateAs('josue60@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:37 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
> +        $supervisorToken = authenticateAs('ward.ruecker@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:37 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
> +        $supervisorToken = authenticateAs('karolann97@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:38 UTC, nugrahaAdhitama commented on tests/Feature/DivisionKPITest.php
>          $supervisorToken = authenticateAs('josue60@example.com', 'rahasia');
This is also used as a variable

2024-09-14 00:39 UTC, nugrahaAdhitama requested changes
For emails and passwords in all files, it's better to put them in a variable, so that if there are changes in the future. Just change the contents of the variable and don't need to search for each one.

2024-09-14 06:52 UTC, NaufalMuh11 commented
Done 🙏

2024-09-23 12:52 UTC, nugrahaAdhitama approved these changes
Approved

2024-09-23 12:52 UTC, merged